### YamlMime:FAQ
metadata:
  title: 常见问题
  description: 及时了解有关 HoloLens 混合现实设备的最新安全问题和答案。
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: 108f2e4c0aa9af251ecb6bc5185c7803ae51b5f7
  ms.sourcegitcommit: e9f746aa41139859edc12fbc21f926c9461da4b3
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 09/13/2021
  ms.locfileid: "126032134"
title: HoloLens 第 1 代安全性常见问题
summary: ''
sections:
- name: 忽略
  questions:
  - question: >
      哪一级别的数据保护 HoloLens 1 提供？
    answer: >
      * 请参阅[HoloLens 第一代 () BitLocker 加密](hololens1-encryption.md)
  - question: >
      使用哪种类型的无线？
    answer: >
      * 802.11 ac 和蓝牙 4.1 LE
  - question: >
      合并了哪些类型的体系结构？  例如：指向点、网格或其他内容？
    answer: >
      * Wi-Fi 可以在基础结构模式下用于与其他无线访问点通信。

      * 如果客户的应用程序支持或其他蓝牙设备，则可以使用蓝牙在多个 HoloLens 之间交谈对等方。
  - question: >
      什么是 FCC ID？
    answer: >
      * C3K1688
  - question: >
      设备运行时所用的频率范围和通道是什么？
    answer: >
      * Wi-fi：频率范围不是用户可配置的，具体取决于所使用的国家/地区。 在美国 Wi-Fi 同时使用 2.4 GHz (1-11) 通道和 5 GHz (36-64，100-165) 通道。

      * 蓝牙：蓝牙使用标准 2.4-2.48 GHz 范围。
  - question: >
      设备是否可以允许或阻止特定的频率？
    answer: >
      * 这不能由用户/设备控制。
  - question: >
      传输和接收的电源级别是什么？ 是否可对其进行调整？ 操作范围是多少？
    answer: >
      * 可在 [此处](https://fccid.io/C3K1688)找到辐射测试标准。 操作范围很大程度上取决于访问点和环境-但大致相当于其他高质量的手机、平板电脑或电脑。
  - question: >
      正常操作的工作周期/生存期是什么？
    answer: >
      * 2-3 小时的活动使用，最多两周的待机时间

      * 电池寿命不可用。
  - question: >
      当工具不在范围内时，传输和接收行为是什么？
    answer: >
      * HoloLens 传输/接收遵循标准 wi-fi/蓝牙模式。 在其范围内，你可能会注意到输入不连贯，直到它完全断开连接，但在返回范围之后，它应该会快速重新连接。
  - question: >
      每平方英尺的部署密度是多少？
    answer: >
      * 这取决于你的网络基础结构。
  - question: >
      设备是否可以使用基础结构作为客户端？
    answer: >
      * 是
  - question: >
      使用哪种协议？
    answer: >
      * HoloLens 不使用任何专用协议
  - question: >
      OS 更新频率– HL OS 更新的频率是多少？  是否有设置的计划？  Microsoft 是否根据需要发布安全修补程序等。
    answer: >
      * Microsoft 提供的操作系统更新与 Windows 10 HoloLens 完全相同。 通常，每年有两个主要更新，一个在春季，一个在秋季。 由于 HoloLens 是 Windows 设备，因此更新概念与任何其他 Windows 设备相同。 Microsoft 根据需要发布安全修补程序，并遵循与任何其他 Windows 设备相同的概念。
  - question: >
      操作系统强化–有哪些选项可用于强化操作系统？  我们可以删除还是关闭不必要的应用程序或服务？
    answer: >
      * HoloLens 的行为类似于智能手机。 它相当于其他新式 Windows 设备。 HoloLens 可通过 Microsoft Intune 或其他新式设备管理解决方案（如 MobileIron、Airwatch 或 Soti）进行管理。 你可以在这些管理系统中设置策略，以将安全策略放在设备上，并强制实施设备。 如果需要，还可以选择删除所有不必要的应用程序。
  - question: >
      软件应用程序将如何管理和更新？ 对于生活在 Microsoft store 中的应用，我们必须使用哪些控制来定义加载哪些应用和应用更新流程？
    answer: >
      * HoloLens 仅通过 Windows 存储获取软件应用程序。 只能安装 Appx 应用程序包，这是为使用 HoloLens 而开发的。 你可以在 Microsoft Store 中看到此项，其中包含用于显示 HoloLens 设备的应用程序旁边的小徽标。 你对应用商店应用程序的管理的任何控制也适用于 HoloLens。 你可以使用官方应用商店或适用于企业的应用程序的概念。 应用可以 (手动过程进行加载，以将应用加载到 Windows 设备上) ，也可以通过 MDM 进行管理，以便在需要时自动从存储中请求应用。
  - question: >
      HoloLens 应用商店中的应用的更新频率是多少？
    answer: >
      * 由于我们遵循 Microsoft Store 的相同概念，并从该处请求应用，因此更新周期由应用程序的开发人员确定。 你必须控制应用商店中的更新机制的所有管理选项也适用于 HoloLens。
  - question: >
      HoloLens 是否有安全启动功能？
    answer: >
      * 是
  - question: >
      是否有能力禁用或断开设备的外围设备支持？
    answer: >
      * 是
  - question: >
      是否有能力控制或禁用设备上的端口？
    answer: >
      * HoloLens 仅包含两个端口 (一个用于耳机，另一个用于充电或连接到 pc) 。 由于功能和恢复原因，无法禁用该端口。
  - question: >
      防病毒，终结点检测，IPS，应用控制允许列表-任何运行防病毒、终结点检测、IP、应用控制允许列表等功能。
    answer: >
      * Windows Holographic for Business (商用套件) 支持 Windows Defender 智能屏幕。 如果防病毒公司创建应用并将其发布到通用 Windows 平台，则可以 HoloLens 下载。 目前，没有任何公司对 HoloLens 执行此操作。

      * 可以通过使用 Microsoft Enterprise Store 来允许应用，你可以在其中仅选择可下载的特定应用。 此外，通过 MDM，你可以锁定可以运行的特定应用程序，甚至还可以在设备上查看。
  - question: >
      如果设备在长时间内处于脱机状态，我们是否可以将设备从生产网络中隔离？  例如： 设备坐在抽屉未通电 (六个月) 并且尚未收到任何更新、修补程序等。 当它试图进入网络时，我们可以标记该网络，并且说在投诉加入网络之前，必须在另一个网络上进行更新。
    answer: >
      * 这是一种可通过 MDM 或本地服务器在基础结构级别管理的内容。 如果设备未满足指定的更新版本，则可以将其标记为不合规。
  - question: >
      Microsoft 是否包括任何后门或对允许 Microsoft 连接到设备以进行屏幕共享或远程支持的服务？
    answer: >
      * 否
  - question: >
      为受信任的通信生成 PKI 证书时，我们希望在设备上生成证书，以便我们知道该证书仅在该设备上、对该设备是唯一的，不能被导出或用于模拟设备。 HoloLens 上是否如此？ 如果不存在，是否有潜在的缓解措施？
    answer: >-
      * SCEP 的 CSR 是在设备本身上生成的。 Intune 和本地 SCEP 连接器通过添加和验证发送到客户端的质询字符串来帮助保护请求。

      * 由于 HoloLens (第一代和第2代) 具有 TPM 模块，因此这些证书将存储在 tpm 模块中，无法提取。 此外，即使可以提取质询字符串，也无法在不同的设备上对其进行验证，从而使证书/密钥在不同设备上不可用。
